"""Diagnostics as Markdown — for a PR comment, an issue, or a paste.

Takes the same payload `forge diagnostics --json` emits, so there is one
source of truth for what a report contains and no second traversal of the
corpus to keep in sync.
"""

from __future__ import annotations

from typing import Any

from .summary import Headline, headline


def render_markdown(payload: dict[str, Any], *, vault_name: str = "vault") -> str:
    facts: Headline = headline(payload)
    out: list[str] = [
        f"# Vault health — {vault_name}",
        "",
        f"**{facts.files:,} Markdown files · {facts.links:,} links**",
        "",
        "| Check | Result |",
        "|---|---|",
    ]

    for label, value, ok in facts.rows():
        mark = "ok" if ok else "**needs attention**"
        out.append(f"| {label} | {value} — {mark} |")

    links = payload.get("links", {})
    unresolved = links.get("unresolved_targets", {})
    if unresolved:
        out += ["", "## Dead links", "", "| Target | Times | Referenced from |", "|---|---:|---|"]
        for target, info in sorted(
            unresolved.items(), key=lambda kv: -kv[1]["count"]
        )[:50]:
            sources = ", ".join(f"`{s}`" for s in info.get("sources", [])[:3])
            more = len(info.get("sources", [])) - 3
            if more > 0:
                sources += f" +{more} more"
            out.append(f"| `{target}` | {info['count']} | {sources} |")

    fm = payload.get("frontmatter", {})
    by_code = fm.get("by_code", {})
    if by_code:
        descriptions = fm.get("code_descriptions", {})
        out += ["", "## Frontmatter", "", "| Code | Files | What it means |", "|---|---:|---|"]
        for code, count in sorted(by_code.items(), key=lambda kv: -kv[1]):
            out.append(f"| {code} | {count} | {descriptions.get(code, '')} |")

    conventions = payload.get("conventions", {})
    if conventions:
        out += ["", "## Conventions", "", conventions.get("resolution_status", "")]
        for conflict in conventions.get("conflicts", []):
            out.append(
                f"- **{conflict['kind']}** — `{conflict['repo_wide']}` "
                f"vs `{conflict['dsa_local']}`"
            )

    out += [
        "",
        "---",
        "",
        "Generated by [forge-kb](https://pypi.org/project/forge-kb/) — "
        "`pip install forge-kb`, then `forge index && forge diagnostics`. "
        "No model, no API key, no network.",
    ]
    return "\n".join(out) + "\n"
